<?php
// Text
$_['text_breadcrumps']            = 'Shipping and payment';
$_['text_title']                  = 'INFORMATION ABOUT DELIVERY';
$_['text_content_title1']         = '1 Procedure for interaction between the Buyer and "Halkmarket" after placing (booking) an order:';
$_['text_content_title2']         = '2 Payment upon delivery of Halkmarket product (s).';
$_['text_content_1_1']            = '"Halkmarket" makes direct contact (to the User on the mobile phone number specified earlier during registration) and provides information about the parameters of the Product (s), confirmation or rejection of the registration (booking), the actual availability of the Product, the actual cost of the Product, storage times for the User of the Product , the order of purchase, the issued (booked) goods and other information with a suitable delivery time for you.';
$_['text_content_1_2']            = 'Upon receipt of the Goods, the User is advised to check the appearance and packaging of the Goods (s), as well as its (their) quantity, completeness, assortment. After the User pays for the Goods, claims for the quality, quantity, dosage of the Goods and the quality of the packaging are not accepted.';
$_['text_content_1_3']            = 'The expiration date of the Goods may differ from the expiration date of the Goods indicated on the Site. At the same time, the remaining shelf life of the Goods should be clarified by the User of the Site by contacting the phone indicated on the site or after confirming the registration (booking) of the order by the Seller-Operator.';
$_['text_content_1_4']            = 'The packaging of the Goods may differ from the packaging of the Goods indicated on the Site. This difference is associated with the manufacturer of the Product.';
$_['text_content_1_5']            = 'High-value product (s) without advance payment are delivered (are) in Ashgabat by courier at the discretion of the Manager of the online store. The amount of the so-called "high-value goods" is determined by the manager of the online store.';
$_['text_content_1_6']            = 'If it is impossible to accept the order at the time agreed with the Seller-operator or refuse it, the buyer is obliged to notify the online store about this within 30 minutes after placing (booking) or before placing (booking) the goods.';
$_['text_content_1_7']            = 'Based on the specified delivery address, the system automatically calculates the cost and delivery time.';
$_['text_content_2_1']            = 'When paying, you confirm your agreement with the terms of sale of the product (s) by the organization X.O "Halkmarket" and the online store "Halkmarket". The user is obliged to pay for the product (s) to the courier at the time of receipt of the product (s). The amount of the goods does not change after the order is placed and approved by the seller-operator.';
$_['text_content_2_2']            = 'Orders in the online store "Halkmarket" can be paid in any convenient way: in cash or by credit card (directly by the owner of the credit card through a handheld terminal).';
$_['text_content_2_3']            = 'Shipping cost is free if the amount of the product (s) exceeds 200 manat.';
$_['text_content_2_4']            = 'If in case the cost of the product (s) turns out to be less than 200 manats, the user will be obliged to negotiate the shipping cost with the Seller-operator. The cost of delivery is determined by the Seller-operator, taking into account the address, weather conditions and time of day. The shipping cost will be included in the Invoice Amount after the final ordering if see clause 6.4.';
$_['text_content_2_5']            = 'A separate receipt for the delivery of goods (s) with a value less than the established amount of 200 manats is not provided.';